version: '3.8'

services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports: 
      - "3000:3000"
    container_name: nest-todo-app-be
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
